version: "3.9"
services:
  web_dev:
    image: smtcomp/smtcomp.github.io:dev
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
        ENVIRONMENT: ${ENVIRONMENT:-dev}
      cache_from:
        - smtcomp/smtcomp.github.io:dev
      target: dev
    volumes:
      - .:/home/user/app
    ports:
      - "8000:8000"
    env_file: .env
  web:
    image: smtcomp/smtcomp.github.io:${IMAGE_TAG}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
        ENVIRONMENT: ${ENVIRONMENT:-dev}
      cache_from:
        - smtcomp/smtcomp.github.io:dev
        - smtcomp/smtcomp.github.io:latest
        - smtcomp/smtcomp.github.io:${IMAGE_TAG}
      target: prod
    ports:
      - "8000:8000"
    env_file: .env
